masneyb/gftp

- src/gtk/Makefile.am
- src/gtk/gftp-gtk.c
- src/gtk/gftp-gtk.h
- src/gtk/platform_specific.c
Add a small macOS foregrounding hack to aid in debugging
> Add support for isolated platform specific cases and a macOS case

- lib/fsplib/fsplib.c
only security fixes
https://sourceforge.net/projects/fsp/files/fsplib/
> fsplib: update to v14.0 [2019-08-16]

- src/gtk/gftp-gtk.c
- src/gtk/menu-items.c
also fixes a bug introduced by 5f2c9b4b2958c9113743c7a29bc5b435fdb9a507
> use standard gtk 'about' dialog

- configure.ac
that extra "0" is confusing, other projects use --enable-gtk2/3
> configure.ac: -gtk30 = -gtk3 (--enable-gtk3) etc

- lib/gftp.h
- lib/misc.c
- src/gtk/misc-gtk.c
2 fengq patches:
report-file-list-info-in-the-host-txt-field.patch
do-not-display-empty-list-info.patch
plus many edits and a function to format the filesize
> gtkui: show file count and total size [local & remote]

- src/gtk/misc-gtk.c
> gtkui: make list info more readable..

- lib/gftp.h
- lib/protocols.c
- src/gtk/gftp-gtk.c
- src/gtk/misc-gtk.c
git-svn-id: svn://orbit.nmr.mgh.harvard.edu/var/lib/gforge/chroot/scmrepos/svn/gftp/trunk@1037 cc038f9a-a97d-43d7-a19c-d23a2e890d88
> put Date before User and Group is more intuitive

- src/gtk/gftp-gtk.c
- src/gtk/gftp-gtk.h
- src/gtk/menu-items.c
> replace GtkFileSelection with GtkFileChooser

- src/gtk/bookmarks.c
- src/gtk/gftp-gtk.c
- src/gtk/gftp-gtk.h
- src/gtk/misc-gtk.c
> use GtkUIManager instead of GtkItemFactory

- src/gtk/bookmarks.c
- src/gtk/gftp-gtk.c
- src/gtk/gftp-gtk.h
- src/gtk/misc-gtk.c
> replace GtkOptionMenu with GtkComboBox

- src/gtk/gftp-gtk.c
menu Remote -> Open Location does not attempt a connection
using the selected protocol.. if you select another protocol
in the toolbar protocol combo
this commit fixes the issue
> gtkui protocol combo (change): set default_protocol

- src/gtk/bookmarks.c
- src/gtk/chmod_dialog.c
- src/gtk/gftp-gtk.c
- src/gtk/gtkui_transfer.c
- src/gtk/misc-gtk.c
- src/gtk/options_dialog.c
- src/gtk/view_dialog.c
> replace gtk_signal by g_signal

- configure.ac
So you can see what is deprecated in GTK2...
> configure.ac: add --enable-gtk-warnings

- src/gtk/misc-gtk.c
> misc-gtk.c: improve MakeYesNoDialog()

- src/gtk/chmod_dialog.c
- src/gtk/delete_dialog.c
- src/gtk/dnd.c
- src/gtk/gftp-gtk.c
- src/gtk/gftp-gtk.h
- src/gtk/gtkui.c
- src/gtk/listbox.c
- src/gtk/menu-items.c
- src/gtk/misc-gtk.c
- src/gtk/transfer.c
- src/gtk/view_dialog.c
* add gftp_get_pixbuf() and pixbuf_hash_table 
this is the first step towards replacing GtkPixmap with GdkPixbuf [gtk2+]
need to replace GtkCList (part 1 & 2) and GtkCTree (part 3 & 4) with GtkTreeView
*  GtkTreeView Part1: replace GtkCList ["listbox"] 
see commit msg.
> GtkTreeView Part1: replace GtkCList ["listbox"]

- lib/sshv2.c
see issue #66 for screenshots and discussion
closes #66
> ssh2: fix for large file sizes

- src/gtk/bookmarks.c
The same behavior and functionality is retained but the TreeView
is set to not be reorderable, the GtkCTree was reorderable and supported drag'n'drop.
It's simpler but the code is more complex.
Making the TreeView reorderable will complicate things to an unknown degree.
The bookmarks hash table and the GtkCTree used to have
references to each other, but now only the TreeView has pointers
to bookmark entries.
Bookmark->cnode was a pointer to a GtkCTreeNode.
Now it's just a flag variable (or a hack).
> GtkTreeView Part3: replace GtkCTree in Bookmarks dialog (bookmarks.c)

- lib/gftp.h
- lib/local.c
This patch which we carry in Debian fixes building on the GNU/Hurd.
> Fix building on Hurd

- README.md
- lib/Makefile.am
- lib/fsp.c
- lib/fsplib.c
- lib/fsplib.h
- lib/gftp.h
- lib/options.h
use only fsplib.c + fsplib.h
and FSP_NOLOCKING
Reverts "remove FSP support (#35)" da2ee474bda1e3fde5aec50c25c8121fad56511c
> restore FSP support

- README.md
> Fix MathML in README.md
