lib/gftp.h, lib/misc.c, lib/protocols.c, lib/sockutils.c, lib/sslcommon.c, src/gtk/gtkui_transfer.c, src/gtk/transfer.c, src/uicommon/gftpui.c, src/uicommon/gftpui.h
With this change gftp will now officially require at least GLib 2.32 since we are no longer calling the deprecated functions
(a future changeset will remove all of the now legacy broken glib 1.x code)
=> Remove usage of all deprecated glib thread functions.

configure.ac, src/gtk/bookmarks.c, src/gtk/chmod_dialog.c, src/gtk/gftp-gtk.c, src/gtk/gtkui.c, src/gtk/gtkui_transfer.c, src/gtk/menu-items.c, src/gtk/misc-gtk.c, src/gtk/options_dialog.c, src/gtk/view_dialog.c
This patch should remove all of the legacy GTK Version 1 support. Since it is rather large, I've broken this up in to separate commits for each file to make it less trouble to review in case I missed something. 
As part of this patch, I have explicitly set the glib check for higher than 2.31.0 due to the gthread api changes.
It compiles and still works for me on OS X but your milage may vary.
=> Gtk1x removal

src/gtk/gftp-gtk.c, src/gtk/gftp-gtk.h, src/gtk/menu-items.c, src/gtk/misc-gtk.c, src/gtk/options_dialog.c
This is the first step towards removing the XPM specific stuff in favor of the GTK Image APIs and other newer graphics magic,.
I've tested this in my local tree by converting connect.xpm to a png image and modifying the line
gftp-gtk.c:  tempwid = toolbar_image (parent, "connect.xpm");
to
gftp-gtk.c:  tempwid = toolbar_image (parent, "connect.png");
In my local tree as well as deleting the connect.xpm and it still functions. I've also tested with restoring the xpm so it should be 100% safe.
For now, we will leave the call as connect.xpm and will convert all of the images in one shot.
Changelog:
Rename some of the icon graphics functions to be a little more generic
Modify the toolbar image loading functions to use the gtk_image api
(This has the benefit of allowing us to load either a …
=> Modify toolbar image loading code to use gtk_image api to support *.xpm or *.png

src/gtk/gftp-gtk.c
As discussed in PR #3 this is a minor cosmetic change that feels a bit more pleasing to the eye (at least mine). I am not sure how this will scale up or down on really large and small screens but it seems like a good value on the few monitors I've tested on under OS X.
=> Add small padding to transfer and message windows

src/gtk/gftp-gtk.c
with gtk_image_new_from_icon_name() and new icon names to remain forward compatible with gtk 3.10+
(I am going to try to feed in various smaller patches like this as I go along to try to keep the ultimate GTK3.x diff to a minimal)
Tested with gtk 2.x on macOS 10.11
=> Replace deprecated gtk_image_new_from_stock() GTK_STOCK_SORT_* 

src/gtk/gftp-gtk.c
versions of GTK.
replace with gtk_image_new_from_icon_name() and new icon names
to remain forward compatible with gtk 3.10+
=> gtk_image_new_from_stock and GTK_STOCK_SORT_* are deprecated in newer

configure.ac, src/gtk/gftp-gtk.c, src/gtk/gftp-gtk.h, src/gtk/misc-gtk.c, src/gtk/options_dialog.c
- Move the gthreads check (there is no need to check for it on gtk3 systems)
- Replace the Tooltips API calls wth the Tooltip API introduced in gtk 2.12
(This is forward compatible with gtk3)
I have not been able to test this as I don't see a change in behavior on the mac, so I believe I may actually be missing tooltips on that platform. Can you apply to a Linux box and see if things still work as expected?
With this patch, we have a few more files that are now compatible with gtk3 but we still have a long way to go.
=> gtk3 tooltips rewrite

src/gtk/gtkui.c
The rename operation fails if the local file already exists [left panel]. I verified that this patch works as expected in debian stretch..
=> gtkui: don't rename file if target file already exists

src/gtk/gftp-gtk.c
git-svn-id: svn://orbit.nmr.mgh.harvard.edu/var/lib/gforge/chroot/scmrepos/svn/gftp/trunk@1001 cc038f9a-a97d-43d7-a19c-d23a2e890d88
=> fix duplicated Ctrl+D shortcut (Bug#577505)

src/gtk/gftp-gtk.c
This is quite handy, it works for local and remote directories
How to test this:
- enter in XX subdirectory
- press Alt + Up and it will show the parent directory
repeat until you reach the root directory: /
git-svn-id: svn://orbit.nmr.mgh.harvard.edu/var/lib/gforge/chroot/scmrepos/svn/gftp/trunk@1005 cc038f9a-a97d-43d7-a19c-d23a2e890d88
=> Alt+Up short cut for moving to the parent dir

src/gtk/gftp-gtk.c
git-svn-id: svn://orbit.nmr.mgh.harvard.edu/var/lib/gforge/chroot/scmrepos/svn/gftp/trunk@1018 cc038f9a-a97d-43d7-a19c-d23a2e890d88
=> port number field can only fit two digits, need more, Bug#570149

configure.ac
gtk2 is enabled by default so if you use --enable-gtk30
is because you really want to use the (broken) gtk3 ui
=> configure.ac: enabling gtk3 automatically disables gtk2

src/gtk/gftp-gtk.c, src/gtk/transfer.c
gtk_timeout is deprecated in gtk2 (and completely removed in gtk3)
=> replace gtk_timeout with g_timeout

src/gtk/bookmarks.c, src/gtk/chmod_dialog.c, src/gtk/gftp-gtk.c, src/gtk/gftp-gtk.h, src/gtk/menu-items.c, src/gtk/misc-gtk.c, src/gtk/options_dialog.c, src/gtk/view_dialog.c
gftp_graphic->GdkPixmap is deprecated in gtk2
cannot remove it yet.. it's used by GtkCList
=> gtkui: (window icon: use GdkPixbuf instead of GdkPixmap)

lib/gftp.h, lib/local.c, lib/sshv2.c, src/gtk/gftp-gtk.c, src/gtk/transfer.c, src/uicommon/gftpui.c
Important bugfix
3 fengq patches:
ignore-permission-error-and-unlistable-directories.patch
permission-deny-and-file-not-exist-do-not-deserve-di.patch
treat-SSH_FX_FAILURE-as-a-non-fatal-error.patch
It seems to work fine.. well at least a sftp connection is less buggy
tested with frs.sourceforge.net 22
=> ssh2 [sftp]: do not disconnect on trivial errors

lib/misc.c, lib/sshv2.c
https://people.gnome.org/~ryanl/glib-docs/glib-Basic-Types.html#G-HAVE-GINT64:CAPS
=> G_HAVE_GINT64 is always defined (and deprecated)

configure.ac, lib/gftp.h
basically all distros and unix systems are [mostly] posix compliant
and the source code [gftp.h] enables all extensions
this also makes it easier to port stuff to some other build system
=> configure.ac: remove some obsolete or unneded checks

src/gtk/gftp-gtk.c
all the other toolbar combos do the same, this was an omission
now the user combo also triggers a connection after hitting enter
although there's the 'activate' signal
=> gtkui: ('user' combo: handle key press events from text entry)

src/gtk/gftp-gtk.h, src/gtk/menu-items.c, src/gtk/misc-gtk.c
If gftp can't find icons it shows many errors like this:
(gftp-gtk:10751): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Now it shows something more meaningful:
(gftp-gtk:11305): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
* gftp: /usr/local/share/gftpdoc.xpm not found
* gftp: /usr/share/gftp/doc.xpm not found
The 1st 'not found' line is the --prefix/datadir (default = /usr/local/share/..)
or the env variable GFTP_SHARE_DIR - see lib/misc.c: gftp_get_share_dir ()
The 2nd 'not found' line is the fallback (/usr/s...), this line is omitted if --prefix=/usr
=> gtkui: get_image_path(): simplify / print missing icon to stderr..

src/gtk/misc-gtk.c
This:
/usr/local/share/gftpdoc.xpm
Becomes:
/usr/local/share/gftp/doc.xpm
=> get_image_path(): fix typo in path1..

configure.ac, src/gtk/Makefile.am, src/gtk/gftp-gtk.c
http://hpux.connect.org.uk/hppd/hpux/Gtk/Development/glib2-2.34.3/readme.html
Notes about GLib 2.32
=====================
* It is no longer necessary to use g_thread_init() or to link against
libgthread.  libglib is now always thread-enabled. Custom thread
system implementations are no longer supported (including errorcheck
mutexes).
=> [glib 2.32] don't check for gthread / don't call g_thread_init()

src/gtk/misc-gtk.c
replace deprecated `(dialog)->vbox` with `gtk_dialog_get_content_area()`
fix gtk_container_set_border_width()
etc
=> misc-gtk.c: improve MakeEditDialog()

src/uicommon/gftpui.c
When running the gftp-gtk or gtfp-text, this msg is displayed:
gFTP 2.0.19 - http://www.gftp.org/
=> gftpui.c: show only gftp version & url in log window

src/gtk/Makefile.am, src/gtk/gftp-gtk.h, src/gtk/gtkcompat.c, src/gtk/gtkcompat.h
It currently defines the following functions:
-   gtk_box_new
-   gtk_button_box_new
-   gtk_scale_new
-   gtk_scale_new_with_range
-   gtk_separator_new
-   gtk_scrollbar_new
-   gtk_paned_new
It makes it easier to update code without adding ifdefs
Example, this
```
#if GTK_CHECK_VERSION (3, 2, 0)
hbox = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 4);
#else //gtk2
hbox = gtk_hbox_new (FALSE, 4);
#endif
```
becomes
```
hbox = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 4);
```
=> src/gtk: add gtkcompat.c / gtkcompat.h

src/gtk/gftp-gtk.h, src/gtk/gtkcompat.h
This patch looks and seems right, however I may be tripping over a bug in the Mac GTK/GLIB keyboard handling.
WIth or without this patch, if I hit the DELETE key, it just moves the selection up to the parent in the bookmarks editor.
I would appreciate it if you could verify the functionality works under linux as is with gtk2 and then see if my patch introduces a regression.
=> src/gtk:  Adapt GTK keypress support to support both gtk2 and gtk3

README.md
In the README file, some titles were wrapped on two lines, which the markdown then understands as "first line is a title, second line is normal text"; I put those titles on the same line in the markdown.
=> Line breaks broke some titles -> put title on the same line

docs/gftp.desktop
Two warnings from lintian:
```
I: gftp-gtk: desktop-entry-contains-encoding-key usr/share/applications/gftp.desktop:2 Encoding
N: 
N:    The Encoding key is now deprecated by the FreeDesktop standard and all
N:    strings are required to be encoded in UTF-8. This desktop entry
N:    explicitly specifies an Encoding of UTF-8, which is harmless but no
N:    longer necessary.
N:    
N:    The desktop-file-validate tool in the desktop-file-utils package is
N:    useful for checking the syntax of desktop entries.
N:    
N:    Refer to
N:    https://specifications.freedesktop.org/desktop-entry-spec/latest/apc.html
N:    for details.
N:    
N:    Severity: info
N:    
N:    Check: menu-format
N: 
I: gftp-gtk: desktop-entry-lacks-keywords-entry usr/share/applications/gftp.desktop
N: 
N:    This …
```
=> Fixes to desktop file

src/gtk/bookmarks.c
Debian handles some warnings as errors, and thus this is a build failure.
```
bookmarks.c:364:34: error: format not a string literal and no format arguments [-Werror=format-security]
364 |                                  error);
|                                  ^~~~~
```
=> Fix format not a string literal and no format arguments in gtk_message_dialog_new

po/nl.po, src/gtk/listbox.c
Update Dutch translation (nl.po). 
Fix spelling error.
I think I did everything right with the po file, but some strings are not visible here. I have the same with another application so probably it is my install. Could you test if all strings show as translated?
Thank you for maintaining gFTP.
Regards, Marcel Pol
=> Update Dutch translation (nl.po). Fix spelling error.

lib/sslcommon.c
20250414:
First commit add support of TLS validation for wildcard domain names (*.domain.tld) present in certificate subjectAltName field
See 20250414 comments
EDIT 20250417:
The second commit add support for OpenSSL SSLKEYLOGFILE to be able to decrypt TLS1.2+ with elliptic curves (ECDHE_*)
See 20250417 comments
=> TLS validation of wildcard subjectAltName domain + SSLKEYLOGFILE support
